name: Build

on:
  push:
    branches:
      - master
  release:
    types:
    - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run Build
      run: |
        npm install
        npm ci
        npm run compile
